#!/bin/bash
cd $HOME
cd $PREFIX/bin/
wget https://raw.githubusercontent.com/rodrigo12xd/MBFREE/main/mb1 && chmod 777 mb1
wget https://raw.githubusercontent.com/rodrigo12xd/MBFREE/main/mb2 && chmod 777 mb2
wget https://raw.githubusercontent.com/rodrigo12xd/MBFREE/main/mb3 && chmod 777 mb3
wget https://raw.githubusercontent.com/rodrigo12xd/MBFREE/main/mb4 && chmod 777 mb4
wget https://raw.githubusercontent.com/rodrigo12xd/MBFREE/main/mb5 && chmod 777 mb5
cd $HOME
