#!/bin/bash
clear
echo -e "\033[1;32m3)50MB\033[1;37m"
echo -e "\033[1;31mTRUE = APROVADO , FALSE = REPROVADO\033[1;37m"
echo "INFORME SEU NÚMERO (DDD+NÚMERO)"
read NUMERO
echo "QUANTAS VEZES DESEJA REPETIR?"
read VEZES
for i in $(seq $VEZES);
do
data=$"msisdn=$NUMERO&campid=19313963-7198-4a33-9511-1c72c7d6152a&opCode=VV" && site=$"http://interatividade.vivo.ddivulga.com/carrotProcess" && curl "${site}" -d "${data}"
echo ""
echo -e "\033[1;32mCONTAGEM:\033[1;37m$i"
done
echo ""
echo -e "        \033[1;33m • \033[1;32mPROGRAMA FINALIZADO\033[1;33m • \033[0m"
echo ""
echo -e "\033[1;31m \033[1;33mPARA INICIAR NOVAMENTE DIGITE: freemb\033[1;37m"
sleep 5
