#!/bin/bash
cd $HOME
cd $PREFIX/bin/
echo "BAIXANDO RECURSOS..."
rm mb1 > /dev/null 2>&1
curl -sO https://raw.githubusercontent.com/rodrigo12xd/MBFREE/main/mb1 && chmod 777 mb1 > /dev/null 2>&1
rm mb2 > /dev/null 2>&1
curl -sO && https://raw.githubusercontent.com/rodrigo12xd/MBFREE/main/mb2 && chmod 777 mb2 > /dev/null 2>&1
rm mb3 > /dev/null 2>&1
curl -sO https://raw.githubusercontent.com/rodrigo12xd/MBFREE/main/mb3 && chmod 777 mb3 > /dev/null 2>&1
rm mb4 > /dev/null 2>&1
curl -sO https://raw.githubusercontent.com/rodrigo12xd/MBFREE/main/mb4 && chmod 777 mb4 > /dev/null 2>&1
rm mb5 > /dev/null 2>&1
curl -sO https://raw.githubusercontent.com/rodrigo12xd/MBFREE/main/mb5 && chmod 777 mb5 > /dev/null 2>&1
rm freemb > /dev/null 2>&1
curl -sO https://raw.githubusercontent.com/rodrigo12xd/MBFREE/main/freemb && chmod 777 freemb > /dev/null 2>&1
cd $HOME
rm mbfree > /dev/null 2>&1
clear
freemb
